[package]
name = "generative_sketches"
version = "0.1.0"
authors = ["Aleks Pickle <aleks.work2222@gmail.com>"]
edition = "2018"

[dependencies]
nannou = "0.14.1"


[[example]]
name = "lines"
path = "src/lines.rs"